import Image from 'next/image'
import Head from 'next/head'
import Main from './components/Main'
import Navbar from './components/Navbar'
import About from './components/About'




export default function Home() {
  return (
    <div>
      <Head>
    <title>Mariam Eneji</title>
    <meta name='description' content='Generated by Next Create app' />
   </Head>
   
   <Navbar />
   <Main />
   <About />

 
    </div>
   
   
  )
}
