import Image from 'next/image'
import Head from 'next/head'
import Main from '../components/Main'
import Navbar from '../components/Navbar'
import About from '../components/About'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
import Contact from '../components/Contact'




export default function Home() {
  return (
    <div>
      <Head>
    <title>Mariam Eneji</title>
    <meta name='description' content='Generated by Next Create app' />
   </Head>
   
   <Navbar />
   <Main />
   <About />
   <Skills />
   <Projects />
   <Contact />

 
    </div>
   
   
  )
}
